// Generated by gencpp from file turtlesim/Kill.msg
// DO NOT EDIT!


#ifndef TURTLESIM_MESSAGE_KILL_H
#define TURTLESIM_MESSAGE_KILL_H

#include <ros/service_traits.h>


#include <turtlesim/KillRequest.h>
#include <turtlesim/KillResponse.h>


namespace turtlesim
{

struct Kill
{

typedef KillRequest Request;
typedef KillResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Kill
} // namespace turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim::Kill > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::turtlesim::Kill&) { return value(); }
};

template<>
struct DataType< ::turtlesim::Kill > {
  static const char* value()
  {
    return "turtlesim/Kill";
  }

  static const char* value(const ::turtlesim::Kill&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim::KillRequest> should match 
// service_traits::MD5Sum< ::turtlesim::Kill > 
template<>
struct MD5Sum< ::turtlesim::KillRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::Kill >::value();
  }
  static const char* value(const ::turtlesim::KillRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::KillRequest> should match 
// service_traits::DataType< ::turtlesim::Kill > 
template<>
struct DataType< ::turtlesim::KillRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim::Kill >::value();
  }
  static const char* value(const ::turtlesim::KillRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim::KillResponse> should match 
// service_traits::MD5Sum< ::turtlesim::Kill > 
template<>
struct MD5Sum< ::turtlesim::KillResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::Kill >::value();
  }
  static const char* value(const ::turtlesim::KillResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::KillResponse> should match 
// service_traits::DataType< ::turtlesim::Kill > 
template<>
struct DataType< ::turtlesim::KillResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim::Kill >::value();
  }
  static const char* value(const ::turtlesim::KillResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_MESSAGE_KILL_H
