// Generated by gencpp from file turtlesim/SetPen.msg
// DO NOT EDIT!


#ifndef TURTLESIM_MESSAGE_SETPEN_H
#define TURTLESIM_MESSAGE_SETPEN_H

#include <ros/service_traits.h>


#include <turtlesim/SetPenRequest.h>
#include <turtlesim/SetPenResponse.h>


namespace turtlesim
{

struct SetPen
{

typedef SetPenRequest Request;
typedef SetPenResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPen
} // namespace turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim::SetPen > {
  static const char* value()
  {
    return "9f452acce566bf0c0954594f69a8e41b";
  }

  static const char* value(const ::turtlesim::SetPen&) { return value(); }
};

template<>
struct DataType< ::turtlesim::SetPen > {
  static const char* value()
  {
    return "turtlesim/SetPen";
  }

  static const char* value(const ::turtlesim::SetPen&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim::SetPenRequest> should match 
// service_traits::MD5Sum< ::turtlesim::SetPen > 
template<>
struct MD5Sum< ::turtlesim::SetPenRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::SetPen >::value();
  }
  static const char* value(const ::turtlesim::SetPenRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::SetPenRequest> should match 
// service_traits::DataType< ::turtlesim::SetPen > 
template<>
struct DataType< ::turtlesim::SetPenRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim::SetPen >::value();
  }
  static const char* value(const ::turtlesim::SetPenRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim::SetPenResponse> should match 
// service_traits::MD5Sum< ::turtlesim::SetPen > 
template<>
struct MD5Sum< ::turtlesim::SetPenResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::SetPen >::value();
  }
  static const char* value(const ::turtlesim::SetPenResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::SetPenResponse> should match 
// service_traits::DataType< ::turtlesim::SetPen > 
template<>
struct DataType< ::turtlesim::SetPenResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim::SetPen >::value();
  }
  static const char* value(const ::turtlesim::SetPenResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_MESSAGE_SETPEN_H
