// Generated by gencpp from file turtlesim/Spawn.msg
// DO NOT EDIT!


#ifndef TURTLESIM_MESSAGE_SPAWN_H
#define TURTLESIM_MESSAGE_SPAWN_H

#include <ros/service_traits.h>


#include <turtlesim/SpawnRequest.h>
#include <turtlesim/SpawnResponse.h>


namespace turtlesim
{

struct Spawn
{

typedef SpawnRequest Request;
typedef SpawnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Spawn
} // namespace turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim::Spawn > {
  static const char* value()
  {
    return "0b2d2e872a8e2887d5ed626f2bf2c561";
  }

  static const char* value(const ::turtlesim::Spawn&) { return value(); }
};

template<>
struct DataType< ::turtlesim::Spawn > {
  static const char* value()
  {
    return "turtlesim/Spawn";
  }

  static const char* value(const ::turtlesim::Spawn&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim::SpawnRequest> should match 
// service_traits::MD5Sum< ::turtlesim::Spawn > 
template<>
struct MD5Sum< ::turtlesim::SpawnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::Spawn >::value();
  }
  static const char* value(const ::turtlesim::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::SpawnRequest> should match 
// service_traits::DataType< ::turtlesim::Spawn > 
template<>
struct DataType< ::turtlesim::SpawnRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim::Spawn >::value();
  }
  static const char* value(const ::turtlesim::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim::SpawnResponse> should match 
// service_traits::MD5Sum< ::turtlesim::Spawn > 
template<>
struct MD5Sum< ::turtlesim::SpawnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::Spawn >::value();
  }
  static const char* value(const ::turtlesim::SpawnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::SpawnResponse> should match 
// service_traits::DataType< ::turtlesim::Spawn > 
template<>
struct DataType< ::turtlesim::SpawnResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim::Spawn >::value();
  }
  static const char* value(const ::turtlesim::SpawnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_MESSAGE_SPAWN_H
