// Generated by gencpp from file turtlesim/TeleportRelative.msg
// DO NOT EDIT!


#ifndef TURTLESIM_MESSAGE_TELEPORTRELATIVE_H
#define TURTLESIM_MESSAGE_TELEPORTRELATIVE_H

#include <ros/service_traits.h>


#include <turtlesim/TeleportRelativeRequest.h>
#include <turtlesim/TeleportRelativeResponse.h>


namespace turtlesim
{

struct TeleportRelative
{

typedef TeleportRelativeRequest Request;
typedef TeleportRelativeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TeleportRelative
} // namespace turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim::TeleportRelative > {
  static const char* value()
  {
    return "9d5c2dcd348ac8f76ce2a4307bd63a13";
  }

  static const char* value(const ::turtlesim::TeleportRelative&) { return value(); }
};

template<>
struct DataType< ::turtlesim::TeleportRelative > {
  static const char* value()
  {
    return "turtlesim/TeleportRelative";
  }

  static const char* value(const ::turtlesim::TeleportRelative&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim::TeleportRelativeRequest> should match 
// service_traits::MD5Sum< ::turtlesim::TeleportRelative > 
template<>
struct MD5Sum< ::turtlesim::TeleportRelativeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::TeleportRelative >::value();
  }
  static const char* value(const ::turtlesim::TeleportRelativeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::TeleportRelativeRequest> should match 
// service_traits::DataType< ::turtlesim::TeleportRelative > 
template<>
struct DataType< ::turtlesim::TeleportRelativeRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim::TeleportRelative >::value();
  }
  static const char* value(const ::turtlesim::TeleportRelativeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim::TeleportRelativeResponse> should match 
// service_traits::MD5Sum< ::turtlesim::TeleportRelative > 
template<>
struct MD5Sum< ::turtlesim::TeleportRelativeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::TeleportRelative >::value();
  }
  static const char* value(const ::turtlesim::TeleportRelativeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::TeleportRelativeResponse> should match 
// service_traits::DataType< ::turtlesim::TeleportRelative > 
template<>
struct DataType< ::turtlesim::TeleportRelativeResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim::TeleportRelative >::value();
  }
  static const char* value(const ::turtlesim::TeleportRelativeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_MESSAGE_TELEPORTRELATIVE_H
