// Generated by gencpp from file rospy_tutorials/BadTwoInts.msg
// DO NOT EDIT!


#ifndef ROSPY_TUTORIALS_MESSAGE_BADTWOINTS_H
#define ROSPY_TUTORIALS_MESSAGE_BADTWOINTS_H

#include <ros/service_traits.h>


#include <rospy_tutorials/BadTwoIntsRequest.h>
#include <rospy_tutorials/BadTwoIntsResponse.h>


namespace rospy_tutorials
{

struct BadTwoInts
{

typedef BadTwoIntsRequest Request;
typedef BadTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BadTwoInts
} // namespace rospy_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rospy_tutorials::BadTwoInts > {
  static const char* value()
  {
    return "60962375a49bd6746d7c85dff75ebb9c";
  }

  static const char* value(const ::rospy_tutorials::BadTwoInts&) { return value(); }
};

template<>
struct DataType< ::rospy_tutorials::BadTwoInts > {
  static const char* value()
  {
    return "rospy_tutorials/BadTwoInts";
  }

  static const char* value(const ::rospy_tutorials::BadTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::rospy_tutorials::BadTwoIntsRequest> should match 
// service_traits::MD5Sum< ::rospy_tutorials::BadTwoInts > 
template<>
struct MD5Sum< ::rospy_tutorials::BadTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rospy_tutorials::BadTwoInts >::value();
  }
  static const char* value(const ::rospy_tutorials::BadTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rospy_tutorials::BadTwoIntsRequest> should match 
// service_traits::DataType< ::rospy_tutorials::BadTwoInts > 
template<>
struct DataType< ::rospy_tutorials::BadTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::rospy_tutorials::BadTwoInts >::value();
  }
  static const char* value(const ::rospy_tutorials::BadTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rospy_tutorials::BadTwoIntsResponse> should match 
// service_traits::MD5Sum< ::rospy_tutorials::BadTwoInts > 
template<>
struct MD5Sum< ::rospy_tutorials::BadTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rospy_tutorials::BadTwoInts >::value();
  }
  static const char* value(const ::rospy_tutorials::BadTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rospy_tutorials::BadTwoIntsResponse> should match 
// service_traits::DataType< ::rospy_tutorials::BadTwoInts > 
template<>
struct DataType< ::rospy_tutorials::BadTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::rospy_tutorials::BadTwoInts >::value();
  }
  static const char* value(const ::rospy_tutorials::BadTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSPY_TUTORIALS_MESSAGE_BADTWOINTS_H
