# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from acl_msgs/SMCData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class SMCData(genpy.Message):
  _md5sum = "c369b167744f4400cc4a61aab630dae0"
  _type = "acl_msgs/SMCData"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
geometry_msgs/Quaternion q_des
geometry_msgs/Quaternion q_act
geometry_msgs/Quaternion q_err

geometry_msgs/Vector3 w_des
geometry_msgs/Vector3 w_act
geometry_msgs/Vector3 w_err

geometry_msgs/Vector3 s
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','q_des','q_act','q_err','w_des','w_act','w_err','s']
  _slot_types = ['std_msgs/Header','geometry_msgs/Quaternion','geometry_msgs/Quaternion','geometry_msgs/Quaternion','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,q_des,q_act,q_err,w_des,w_act,w_err,s

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SMCData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.q_des is None:
        self.q_des = geometry_msgs.msg.Quaternion()
      if self.q_act is None:
        self.q_act = geometry_msgs.msg.Quaternion()
      if self.q_err is None:
        self.q_err = geometry_msgs.msg.Quaternion()
      if self.w_des is None:
        self.w_des = geometry_msgs.msg.Vector3()
      if self.w_act is None:
        self.w_act = geometry_msgs.msg.Vector3()
      if self.w_err is None:
        self.w_err = geometry_msgs.msg.Vector3()
      if self.s is None:
        self.s = geometry_msgs.msg.Vector3()
    else:
      self.header = std_msgs.msg.Header()
      self.q_des = geometry_msgs.msg.Quaternion()
      self.q_act = geometry_msgs.msg.Quaternion()
      self.q_err = geometry_msgs.msg.Quaternion()
      self.w_des = geometry_msgs.msg.Vector3()
      self.w_act = geometry_msgs.msg.Vector3()
      self.w_err = geometry_msgs.msg.Vector3()
      self.s = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_24d().pack(_x.q_des.x, _x.q_des.y, _x.q_des.z, _x.q_des.w, _x.q_act.x, _x.q_act.y, _x.q_act.z, _x.q_act.w, _x.q_err.x, _x.q_err.y, _x.q_err.z, _x.q_err.w, _x.w_des.x, _x.w_des.y, _x.w_des.z, _x.w_act.x, _x.w_act.y, _x.w_act.z, _x.w_err.x, _x.w_err.y, _x.w_err.z, _x.s.x, _x.s.y, _x.s.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.q_des is None:
        self.q_des = geometry_msgs.msg.Quaternion()
      if self.q_act is None:
        self.q_act = geometry_msgs.msg.Quaternion()
      if self.q_err is None:
        self.q_err = geometry_msgs.msg.Quaternion()
      if self.w_des is None:
        self.w_des = geometry_msgs.msg.Vector3()
      if self.w_act is None:
        self.w_act = geometry_msgs.msg.Vector3()
      if self.w_err is None:
        self.w_err = geometry_msgs.msg.Vector3()
      if self.s is None:
        self.s = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 192
      (_x.q_des.x, _x.q_des.y, _x.q_des.z, _x.q_des.w, _x.q_act.x, _x.q_act.y, _x.q_act.z, _x.q_act.w, _x.q_err.x, _x.q_err.y, _x.q_err.z, _x.q_err.w, _x.w_des.x, _x.w_des.y, _x.w_des.z, _x.w_act.x, _x.w_act.y, _x.w_act.z, _x.w_err.x, _x.w_err.y, _x.w_err.z, _x.s.x, _x.s.y, _x.s.z,) = _get_struct_24d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_24d().pack(_x.q_des.x, _x.q_des.y, _x.q_des.z, _x.q_des.w, _x.q_act.x, _x.q_act.y, _x.q_act.z, _x.q_act.w, _x.q_err.x, _x.q_err.y, _x.q_err.z, _x.q_err.w, _x.w_des.x, _x.w_des.y, _x.w_des.z, _x.w_act.x, _x.w_act.y, _x.w_act.z, _x.w_err.x, _x.w_err.y, _x.w_err.z, _x.s.x, _x.s.y, _x.s.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.q_des is None:
        self.q_des = geometry_msgs.msg.Quaternion()
      if self.q_act is None:
        self.q_act = geometry_msgs.msg.Quaternion()
      if self.q_err is None:
        self.q_err = geometry_msgs.msg.Quaternion()
      if self.w_des is None:
        self.w_des = geometry_msgs.msg.Vector3()
      if self.w_act is None:
        self.w_act = geometry_msgs.msg.Vector3()
      if self.w_err is None:
        self.w_err = geometry_msgs.msg.Vector3()
      if self.s is None:
        self.s = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 192
      (_x.q_des.x, _x.q_des.y, _x.q_des.z, _x.q_des.w, _x.q_act.x, _x.q_act.y, _x.q_act.z, _x.q_act.w, _x.q_err.x, _x.q_err.y, _x.q_err.z, _x.q_err.w, _x.w_des.x, _x.w_des.y, _x.w_des.z, _x.w_act.x, _x.w_act.y, _x.w_act.z, _x.w_err.x, _x.w_err.y, _x.w_err.z, _x.s.x, _x.s.y, _x.s.z,) = _get_struct_24d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_24d = None
def _get_struct_24d():
    global _struct_24d
    if _struct_24d is None:
        _struct_24d = struct.Struct("<24d")
    return _struct_24d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
