# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from acl_msgs/ViconState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class ViconState(genpy.Message):
  _md5sum = "b7e43266dac9a0f8e73e309a192f76b9"
  _type = "acl_msgs/ViconState"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
geometry_msgs/Pose pose
geometry_msgs/Vector3 Eulers
geometry_msgs/Twist twist
geometry_msgs/Vector3 pos_accel
geometry_msgs/Vector3 Eulers_accel
bool has_pose
bool has_twist
bool has_accel
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular
"""
  __slots__ = ['header','pose','Eulers','twist','pos_accel','Eulers_accel','has_pose','has_twist','has_accel']
  _slot_types = ['std_msgs/Header','geometry_msgs/Pose','geometry_msgs/Vector3','geometry_msgs/Twist','geometry_msgs/Vector3','geometry_msgs/Vector3','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,pose,Eulers,twist,pos_accel,Eulers_accel,has_pose,has_twist,has_accel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ViconState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.Eulers is None:
        self.Eulers = geometry_msgs.msg.Vector3()
      if self.twist is None:
        self.twist = geometry_msgs.msg.Twist()
      if self.pos_accel is None:
        self.pos_accel = geometry_msgs.msg.Vector3()
      if self.Eulers_accel is None:
        self.Eulers_accel = geometry_msgs.msg.Vector3()
      if self.has_pose is None:
        self.has_pose = False
      if self.has_twist is None:
        self.has_twist = False
      if self.has_accel is None:
        self.has_accel = False
    else:
      self.header = std_msgs.msg.Header()
      self.pose = geometry_msgs.msg.Pose()
      self.Eulers = geometry_msgs.msg.Vector3()
      self.twist = geometry_msgs.msg.Twist()
      self.pos_accel = geometry_msgs.msg.Vector3()
      self.Eulers_accel = geometry_msgs.msg.Vector3()
      self.has_pose = False
      self.has_twist = False
      self.has_accel = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_22d3B().pack(_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.Eulers.x, _x.Eulers.y, _x.Eulers.z, _x.twist.linear.x, _x.twist.linear.y, _x.twist.linear.z, _x.twist.angular.x, _x.twist.angular.y, _x.twist.angular.z, _x.pos_accel.x, _x.pos_accel.y, _x.pos_accel.z, _x.Eulers_accel.x, _x.Eulers_accel.y, _x.Eulers_accel.z, _x.has_pose, _x.has_twist, _x.has_accel))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.Eulers is None:
        self.Eulers = geometry_msgs.msg.Vector3()
      if self.twist is None:
        self.twist = geometry_msgs.msg.Twist()
      if self.pos_accel is None:
        self.pos_accel = geometry_msgs.msg.Vector3()
      if self.Eulers_accel is None:
        self.Eulers_accel = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 179
      (_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.Eulers.x, _x.Eulers.y, _x.Eulers.z, _x.twist.linear.x, _x.twist.linear.y, _x.twist.linear.z, _x.twist.angular.x, _x.twist.angular.y, _x.twist.angular.z, _x.pos_accel.x, _x.pos_accel.y, _x.pos_accel.z, _x.Eulers_accel.x, _x.Eulers_accel.y, _x.Eulers_accel.z, _x.has_pose, _x.has_twist, _x.has_accel,) = _get_struct_22d3B().unpack(str[start:end])
      self.has_pose = bool(self.has_pose)
      self.has_twist = bool(self.has_twist)
      self.has_accel = bool(self.has_accel)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_22d3B().pack(_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.Eulers.x, _x.Eulers.y, _x.Eulers.z, _x.twist.linear.x, _x.twist.linear.y, _x.twist.linear.z, _x.twist.angular.x, _x.twist.angular.y, _x.twist.angular.z, _x.pos_accel.x, _x.pos_accel.y, _x.pos_accel.z, _x.Eulers_accel.x, _x.Eulers_accel.y, _x.Eulers_accel.z, _x.has_pose, _x.has_twist, _x.has_accel))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.Eulers is None:
        self.Eulers = geometry_msgs.msg.Vector3()
      if self.twist is None:
        self.twist = geometry_msgs.msg.Twist()
      if self.pos_accel is None:
        self.pos_accel = geometry_msgs.msg.Vector3()
      if self.Eulers_accel is None:
        self.Eulers_accel = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 179
      (_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.Eulers.x, _x.Eulers.y, _x.Eulers.z, _x.twist.linear.x, _x.twist.linear.y, _x.twist.linear.z, _x.twist.angular.x, _x.twist.angular.y, _x.twist.angular.z, _x.pos_accel.x, _x.pos_accel.y, _x.pos_accel.z, _x.Eulers_accel.x, _x.Eulers_accel.y, _x.Eulers_accel.z, _x.has_pose, _x.has_twist, _x.has_accel,) = _get_struct_22d3B().unpack(str[start:end])
      self.has_pose = bool(self.has_pose)
      self.has_twist = bool(self.has_twist)
      self.has_accel = bool(self.has_accel)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_22d3B = None
def _get_struct_22d3B():
    global _struct_22d3B
    if _struct_22d3B is None:
        _struct_22d3B = struct.Struct("<22d3B")
    return _struct_22d3B
