// Generated by gencpp from file acl_msgs/QuadMotors.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_QUADMOTORS_H
#define ACL_MSGS_MESSAGE_QUADMOTORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace acl_msgs
{
template <class ContainerAllocator>
struct QuadMotors_
{
  typedef QuadMotors_<ContainerAllocator> Type;

  QuadMotors_()
    : header()
    , m1(0.0)
    , m2(0.0)
    , m3(0.0)
    , m4(0.0)  {
    }
  QuadMotors_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , m1(0.0)
    , m2(0.0)
    , m3(0.0)
    , m4(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _m1_type;
  _m1_type m1;

   typedef double _m2_type;
  _m2_type m2;

   typedef double _m3_type;
  _m3_type m3;

   typedef double _m4_type;
  _m4_type m4;





  typedef boost::shared_ptr< ::acl_msgs::QuadMotors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::QuadMotors_<ContainerAllocator> const> ConstPtr;

}; // struct QuadMotors_

typedef ::acl_msgs::QuadMotors_<std::allocator<void> > QuadMotors;

typedef boost::shared_ptr< ::acl_msgs::QuadMotors > QuadMotorsPtr;
typedef boost::shared_ptr< ::acl_msgs::QuadMotors const> QuadMotorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::QuadMotors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::QuadMotors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace acl_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'acl_msgs': ['/home/peterli/catkin_ws_com/src/acl_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::QuadMotors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::QuadMotors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::QuadMotors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::QuadMotors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::QuadMotors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::QuadMotors_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::QuadMotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a3dd2047028326e263cac92ef3c3c45";
  }

  static const char* value(const ::acl_msgs::QuadMotors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a3dd2047028326eULL;
  static const uint64_t static_value2 = 0x263cac92ef3c3c45ULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::QuadMotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/QuadMotors";
  }

  static const char* value(const ::acl_msgs::QuadMotors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::QuadMotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 m1\n\
float64 m2\n\
float64 m3\n\
float64 m4\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::acl_msgs::QuadMotors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::QuadMotors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.m1);
      stream.next(m.m2);
      stream.next(m.m3);
      stream.next(m.m4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadMotors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::QuadMotors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::QuadMotors_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "m1: ";
    Printer<double>::stream(s, indent + "  ", v.m1);
    s << indent << "m2: ";
    Printer<double>::stream(s, indent + "  ", v.m2);
    s << indent << "m3: ";
    Printer<double>::stream(s, indent + "  ", v.m3);
    s << indent << "m4: ";
    Printer<double>::stream(s, indent + "  ", v.m4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_QUADMOTORS_H
