// Generated by gencpp from file acl_msgs/SMCData.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_SMCDATA_H
#define ACL_MSGS_MESSAGE_SMCDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace acl_msgs
{
template <class ContainerAllocator>
struct SMCData_
{
  typedef SMCData_<ContainerAllocator> Type;

  SMCData_()
    : header()
    , q_des()
    , q_act()
    , q_err()
    , w_des()
    , w_act()
    , w_err()
    , s()  {
    }
  SMCData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , q_des(_alloc)
    , q_act(_alloc)
    , q_err(_alloc)
    , w_des(_alloc)
    , w_act(_alloc)
    , w_err(_alloc)
    , s(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _q_des_type;
  _q_des_type q_des;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _q_act_type;
  _q_act_type q_act;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _q_err_type;
  _q_err_type q_err;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _w_des_type;
  _w_des_type w_des;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _w_act_type;
  _w_act_type w_act;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _w_err_type;
  _w_err_type w_err;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _s_type;
  _s_type s;





  typedef boost::shared_ptr< ::acl_msgs::SMCData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::SMCData_<ContainerAllocator> const> ConstPtr;

}; // struct SMCData_

typedef ::acl_msgs::SMCData_<std::allocator<void> > SMCData;

typedef boost::shared_ptr< ::acl_msgs::SMCData > SMCDataPtr;
typedef boost::shared_ptr< ::acl_msgs::SMCData const> SMCDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::SMCData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::SMCData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace acl_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'acl_msgs': ['/home/peterli/catkin_ws_com/src/acl_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::SMCData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::SMCData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::SMCData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::SMCData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::SMCData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::SMCData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::SMCData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c369b167744f4400cc4a61aab630dae0";
  }

  static const char* value(const ::acl_msgs::SMCData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc369b167744f4400ULL;
  static const uint64_t static_value2 = 0xcc4a61aab630dae0ULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::SMCData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/SMCData";
  }

  static const char* value(const ::acl_msgs::SMCData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::SMCData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Quaternion q_des\n\
geometry_msgs/Quaternion q_act\n\
geometry_msgs/Quaternion q_err\n\
\n\
geometry_msgs/Vector3 w_des\n\
geometry_msgs/Vector3 w_act\n\
geometry_msgs/Vector3 w_err\n\
\n\
geometry_msgs/Vector3 s\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::acl_msgs::SMCData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::SMCData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.q_des);
      stream.next(m.q_act);
      stream.next(m.q_err);
      stream.next(m.w_des);
      stream.next(m.w_act);
      stream.next(m.w_err);
      stream.next(m.s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SMCData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::SMCData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::SMCData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "q_des: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.q_des);
    s << indent << "q_act: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.q_act);
    s << indent << "q_err: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.q_err);
    s << indent << "w_des: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.w_des);
    s << indent << "w_act: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.w_act);
    s << indent << "w_err: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.w_err);
    s << indent << "s: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_SMCDATA_H
