// Generated by gencpp from file roscpp_tutorials/TwoInts.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_TWOINTS_H
#define ROSCPP_TUTORIALS_MESSAGE_TWOINTS_H

#include <ros/service_traits.h>


#include <roscpp_tutorials/TwoIntsRequest.h>
#include <roscpp_tutorials/TwoIntsResponse.h>


namespace roscpp_tutorials
{

struct TwoInts
{

typedef TwoIntsRequest Request;
typedef TwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TwoInts
} // namespace roscpp_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roscpp_tutorials::TwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::roscpp_tutorials::TwoInts&) { return value(); }
};

template<>
struct DataType< ::roscpp_tutorials::TwoInts > {
  static const char* value()
  {
    return "roscpp_tutorials/TwoInts";
  }

  static const char* value(const ::roscpp_tutorials::TwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::roscpp_tutorials::TwoIntsRequest> should match 
// service_traits::MD5Sum< ::roscpp_tutorials::TwoInts > 
template<>
struct MD5Sum< ::roscpp_tutorials::TwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roscpp_tutorials::TwoInts >::value();
  }
  static const char* value(const ::roscpp_tutorials::TwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roscpp_tutorials::TwoIntsRequest> should match 
// service_traits::DataType< ::roscpp_tutorials::TwoInts > 
template<>
struct DataType< ::roscpp_tutorials::TwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::roscpp_tutorials::TwoInts >::value();
  }
  static const char* value(const ::roscpp_tutorials::TwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roscpp_tutorials::TwoIntsResponse> should match 
// service_traits::MD5Sum< ::roscpp_tutorials::TwoInts > 
template<>
struct MD5Sum< ::roscpp_tutorials::TwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roscpp_tutorials::TwoInts >::value();
  }
  static const char* value(const ::roscpp_tutorials::TwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roscpp_tutorials::TwoIntsResponse> should match 
// service_traits::DataType< ::roscpp_tutorials::TwoInts > 
template<>
struct DataType< ::roscpp_tutorials::TwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::roscpp_tutorials::TwoInts >::value();
  }
  static const char* value(const ::roscpp_tutorials::TwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_TWOINTS_H
